🔥[HOTFIX]: rontend bug fix
Duke-MatSci/materialsmine pull request #307
Opened 2023-02-16 18:41 UTC by tholulomo

2023-02-17 03:02 UTC, aswallace requested changes
When I pulled these changes and tried it out locally, the autosuggest menu is still staying open when I search. I also left a comment about the snackbar infinite duration

2023-02-17 03:09 UTC, aswallace commented
I tried this out some more, and it turns out that the autosuggest goes away if I wait for it to appear and then hit enter. But since it doesn't show up right away, I normally hit enter before it renders, so that by the time it re-navigates to the search result, the menu only then renders and then gets stuck there. (I know this isn't the best explanation, let me know if I can clarify)

2023-02-18 02:10 UTC, tholulomo commented on app/src/components/Snackbar.vue
> +    <md-snackbar :md-position="position" :md-active.sync="show" :md-duration="isInfinity">
The intent for adding infinity is to ensure that persistency while making sure the user is aware of the error. I noticed without that, it display the error and it's gone before you notice. Also I am converting it to ternary in my current branch to accommodate duration. Later, we can add a listener to dismiss if any other button is clicked other than the action button

2023-02-20 21:43 UTC, tholulomo commented
> I tried out the explorer search some more, and it turns out that the autosuggest goes away if I wait for it to appear and then hit enter. But since it doesn't show up right away, I normally hit enter before it renders, so that by the time it re-navigates to the search result, the menu only then renders and then gets stuck there. (I know this isn't the best explanation, let me know if I can clarify)

The browser sets that input field out of focus as soon as you press enter and I can notice a latency in respone.

2023-02-20 21:57 UTC, tholulomo commented
This PR is now merged into #308

2023-02-20 21:57 UTC, closed without merging